# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: PracticePool

variables:
  buildConfiguration: 'Release'
  artifactName: 'drop'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: '**/*Tests/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(artifactName)'
    publishLocation: 'Container'

# # Deployment section
# - task: AzureWebApp@1
#   inputs:
#     # azureSubscription: '<Your-Service-Connection>'
#     # appName: '<Your-App-Service-Name>'
#     # package: '$(Build.ArtifactStagingDirectory)'
#     azureSubscription: 'serviceconnectionpractice'  
#     package: '$(Build.ArtifactStagingDirectory)'
#     appType: 'webApp'
#     WebAppName: 'harshtestapi'
#     DeploymentType: 'webDeploy'
